"""Preset instruments: single list for the symbol dropdown and /api/scan_symbols (App preset list).

Edit this file to change which symbols appear in instrument recommendations when not using MT5 Market Watch.
Broker suffixes may differ (e.g. EURUSD.r, DE40_c) — add the exact name in MT5 and use Market Watch mode to scan.
"""

from __future__ import annotations

# (mt5_symbol, display_label)
PRESET_SYMBOLS: list[tuple[str, str]] = [
    # --- Forex majors ---
    ("EURUSD", "EUR/USD"),
    ("GBPUSD", "GBP/USD"),
    ("USDJPY", "USD/JPY"),
    ("USDCHF", "USD/CHF"),
    ("AUDUSD", "AUD/USD"),
    ("NZDUSD", "NZD/USD"),
    ("USDCAD", "USD/CAD"),
    # --- Forex crosses ---
    ("EURGBP", "EUR/GBP"),
    ("EURJPY", "EUR/JPY"),
    ("GBPJPY", "GBP/JPY"),
    ("EURCHF", "EUR/CHF"),
    ("CHFJPY", "CHF/JPY"),
    ("CHFSGD", "CHF/SGD"),
    ("SGDJPY", "SGD/JPY"),
    ("HKDJPY", "HKD/JPY"),
    ("EURAUD", "EUR/AUD"),
    ("EURCAD", "EUR/CAD"),
    ("EURNZD", "EUR/NZD"),
    ("EURMXN", "EUR/MXN"),
    ("EURTRY", "EUR/TRY"),
    ("EURZAR", "EUR/ZAR"),
    ("EURPLN", "EUR/PLN"),
    ("EURNOK", "EUR/NOK"),
    ("EURSEK", "EUR/SEK"),
    ("GBPCHF", "GBP/CHF"),
    ("GBPAUD", "GBP/AUD"),
    ("GBPCAD", "GBP/CAD"),
    ("GBPNZD", "GBP/NZD"),
    ("GBPSEK", "GBP/SEK"),
    ("GBPZAR", "GBP/ZAR"),
    ("GBPNOK", "GBP/NOK"),
    ("GBPTRY", "GBP/TRY"),
    ("AUDJPY", "AUD/JPY"),
    ("NZDJPY", "NZD/JPY"),
    ("CADJPY", "CAD/JPY"),
    ("AUDNZD", "AUD/NZD"),
    ("AUDCAD", "AUD/CAD"),
    ("AUDCHF", "AUD/CHF"),
    ("AUDSGD", "AUD/SGD"),
    ("AUDHKD", "AUD/HKD"),
    ("AUDMXN", "AUD/MXN"),
    ("CADCHF", "CAD/CHF"),
    ("CADSGD", "CAD/SGD"),
    ("CADHKD", "CAD/HKD"),
    ("NZDCAD", "NZD/CAD"),
    ("NZDCHF", "NZD/CHF"),
    ("NZDSGD", "NZD/SGD"),
    ("NZDHKD", "NZD/HKD"),
    # --- Forex exotics ---
    ("USDTRY", "USD/TRY"),
    ("USDZAR", "USD/ZAR"),
    ("USDMXN", "USD/MXN"),
    ("USDSEK", "USD/SEK"),
    ("USDNOK", "USD/NOK"),
    ("USDPLN", "USD/PLN"),
    ("USDHKD", "USD/HKD"),
    ("USDSGD", "USD/SGD"),
    ("USDCZK", "USD/CZK"),
    ("USDHUF", "USD/HUF"),
    # --- Commodities / metals ---
    ("XAUUSD", "XAU/USD (Gold)"),
    ("XAGUSD", "XAG/USD (Silver)"),
    ("XPDUSD", "XPD/USD (Palladium)"),
    ("XPTUSD", "XPT/USD (Platinum)"),
    # --- Energy (CFDs) ---
    ("USOIL", "WTI Crude (USOIL)"),
    ("UKOIL", "Brent (UKOIL)"),
    ("NGAS", "Natural gas"),
    # --- Index & futures-style CFDs ---
    ("US500", "S&P 500"),
    ("US30", "Dow Jones"),
    ("US100", "Nasdaq 100"),
    ("NAS100", "Nasdaq 100 (alt)"),
    ("US2000", "Russell 2000"),
    ("DE40", "DAX 40"),
    ("DE30", "DAX (alt)"),
    ("GER40", "DAX (GER40)"),
    ("FR40", "CAC 40"),
    ("ES35", "IBEX 35"),
    ("IT40", "FTSE MIB"),
    ("UK100", "FTSE 100"),
    ("EU50", "Euro Stoxx 50"),
    ("JP225", "Nikkei 225"),
    ("HK50", "Hang Seng"),
    ("AUS200", "ASX 200"),
    ("CHINA50", "China A50"),
    ("RUS50", "MOEX / Russia 50"),
    ("USDX", "US Dollar Index"),
    ("VOLATILITY75", "VIX CFD"),
    # --- Cryptocurrency vs USD ---
    ("BTCUSD", "Bitcoin / USD"),
    ("ETHUSD", "Ethereum / USD"),
    ("LTCUSD", "Litecoin / USD"),
    ("XRPUSD", "Ripple / USD"),
    ("BCHUSD", "Bitcoin Cash / USD"),
    ("ADAUSD", "Cardano / USD"),
    ("DOTUSD", "Polkadot / USD"),
    ("SOLUSD", "Solana / USD"),
    ("AVAXUSD", "Avalanche / USD"),
    ("DOGEUSD", "Dogecoin / USD"),
    ("TRXUSD", "Tron / USD"),
    ("LINKUSD", "Chainlink / USD"),
    ("MATICUSD", "Polygon / USD"),
    ("BNBUSD", "BNB / USD"),
    ("ATOMUSD", "Cosmos / USD"),
    ("XLMUSD", "Stellar / USD"),
    ("UNIUSD", "Uniswap / USD"),
    ("NEARUSD", "NEAR / USD"),
]

# Preset symbols that are NOT FX spot (metals, energies, indices, crypto) — used for forex-only scans.
_NOT_FOREX_SPOT: frozenset[str] = frozenset(
    {
        "XAUUSD",
        "XAGUSD",
        "XPDUSD",
        "XPTUSD",
        "USOIL",
        "UKOIL",
        "NGAS",
        "US500",
        "US30",
        "US100",
        "NAS100",
        "US2000",
        "DE40",
        "DE30",
        "GER40",
        "FR40",
        "ES35",
        "IT40",
        "UK100",
        "EU50",
        "JP225",
        "HK50",
        "AUS200",
        "CHINA50",
        "RUS50",
        "USDX",
        "VOLATILITY75",
        "BTCUSD",
        "ETHUSD",
        "LTCUSD",
        "XRPUSD",
        "BCHUSD",
        "ADAUSD",
        "DOTUSD",
        "SOLUSD",
        "AVAXUSD",
        "DOGEUSD",
        "TRXUSD",
        "LINKUSD",
        "MATICUSD",
        "BNBUSD",
        "ATOMUSD",
        "XLMUSD",
        "UNIUSD",
        "NEARUSD",
    }
)


def preset_forex_pairs() -> list[tuple[str, str]]:
    """Currency pairs only from :data:`PRESET_SYMBOLS` (for forex-only recommendation scans)."""
    return [(c, lab) for c, lab in PRESET_SYMBOLS if c not in _NOT_FOREX_SPOT]
